apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: shubhamsingh987/test:v4
        name: test
        ports:
        - containerPort: 8080
